### ISSUE TITLE
NameError: name 'read_image_file' is not defined

### ISSUE THREAD

**Issue by arrogant-R** [chenpf1025/IDN#2]
Hello, your SEAL method has greatly inspired me, which has sparked my interest in your code implementation.  However, I encountered an "undefined function in dataset.py" error when running your code. Could you please supplement the definition of this part of the function?
``dataset.py", line 143: NameError: name 'read_image_file' is not defined``

**Comment by chenpf1025** [comment]
In previous versions, this function might have been included automatically. Now, while this function is still present in the official implementation, you may need to include it manually, for example: `from torchvision.datasets.mnist import read_image_file, read_label_file`.

**Comment by arrogant-R** [comment]
thanks, it works!
